@startuml
'https://plantuml.com/class-diagram

Class Persona{
    -nombre : String
    -apellido : String
    -cedula : String
    -edad : String
}

Class Anunciante{}

Class Comprador{}

Persona <|-- Anunciante
Persona <|-- Comprador

@enduml